### PR TITLE
Add structs

### PR DESCRIPTION
**Pull request by axxu**
is this better?

### CODE REVIEW

**Comment by ohEmily** [comment]
yes, this is the correct order. :dancer: I'll review this asap!

**Comment by ohEmily** [comment]
Hey guys,

This branch doesn't work properly for me. Could you instruct me how to get it working? Here's what I tried:

```
git checkout a37ba16 // last commit this has in common with master
git checkout -b add_structs // call that point in the history add_structs
git pull origin add_structs // replay the commits above onto there
make
```

Doing this yields the attached output.

Let me know what I'm doing differently. Thank you!
[make_output.txt](https://github.com/DemocritusLang/Democritus/files/247601/make_output.txt)

**Comment by ohEmily** [comment]
Okay part of the problem or a separate problem is definitely that this branch wasn't created off of master, so the histories seem to diverge significantly.

**Comment by axxu** [comment]
[make_output.txt](https://github.com/DemocritusLang/Democritus/files/247773/make_output.txt)

**Comment by axxu** [comment]
YAY!!!

**Comment by ohEmily** [comment]
Just so I can be on the same page, why did we merge this? Even Amy's output is full of warnings.

**Comment by kyle--lee** [comment]
We thought you were deadlocked on threads waiting for structs to be finished. I'll take a look at the warnings now.

**Pull request merged**
